//SUCCESS
export const CREATE_ADMIN_SUCCESS = 'CREATE_ADMIN_SUCCESS';
export const SIGN_IN_ADMIN_SUCCESS = 'SIGN_IN_ADMIN_SUCCESS';
export const GET_ADMIN_INFO_SUCCESS = 'GET_ADMIN_INFO_SUCCESS';

//ERROR
export const ERROR_CREATE_ADMIN = 'ERROR_CREATE_ADMIN';
export const ERROR_SIGN_IN_ADMIN = 'ERROR_SIGN_IN_ADMIN';
export const ERROR_GET_ADMIN_INFO = 'ERROR_GET_ADMIN_INFO';
