// Success
export const SIGN_SUCCESS = 'SIGN_SUCCESS';

// Error
export const ACCOUNT_ALREADY_LINK_TO_THIS_SOCIAL_MEDIA =
  'ACCOUNT_ALREADY_LINK_TO_THIS_SOCIAL_MEDIA';
export const USER_NOT_EXIST = 'USER_NOT_EXIST';
