// Success
export const SIGN_SUCCESS = 'SIGN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';

// Error
export const ERROR_ACCOUNT_ALREADY_LINK_TO_THIS_SOCIAL_MEDIA =
  'ACCOUNT_ALREADY_LINK_TO_THIS_SOCIAL_MEDIA';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const ERROR_EMAIL_HAS_BEEN_USED = 'ERROR_EMAIL_HAS_BEEN_USED';
export const ERROR_USER_NOT_EXIST = 'ERROR_USER_NOT_EXIST';
export const ERROR_PASSWORD_NOT_MATCH = 'ERROR_PASSWORD_NOT_MATCH';
export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
