// Success
export const SIGN_SUCCESS = 'SIGN_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';

// Error
export const ACCOUNT_ALREADY_LINK_TO_THIS_SOCIAL_MEDIA =
  'ACCOUNT_ALREADY_LINK_TO_THIS_SOCIAL_MEDIA';
export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const ERROR_EMAIL_HAS_BEEN_USED = 'ERROR_EMAIL_HAS_BEEN_USED';
