// ERROR
export const ERROR_CREATE_BRAND = 'ERROR_CREATE_BRAND';
export const ERROR_BRAND_NAME_EXISTED = 'ERROR_BRAND_NAME_EXISTED';
export const ERROR_UPDATE_BRAND = 'ERROR_UPDATE_BRAND';
export const ERROR_BRAND_NOT_EXIST = 'ERROR_BRAND_NOT_EXIST';
export const ERROR_NO_FIELD_TO_UPDATE = 'ERROR_NO_FIELD_TO_UPDATE';
export const ERROR_DELETE_BRAND = 'ERROR_DELETE_BRAND';
export const ERROR_GET_BRAND = 'ERROR_GET_BRAND';
export const ERROR_GET_BRANDS = 'ERROR_GET_BRANDS';
export const ERROR_GET_BRANDS_BY_CATEGORY = 'ERROR_GET_BRANDS_BY_CATEGORY';
export const ERROR_GET_BRANDS_RANKING_SELL = 'ERROR_GET_BRANDS_RANKING_SELL';
export const ERROR_GET_BRAND_NAME_BY_ID = 'ERROR_GET_BRAND_NAME_BY_ID';
export const ERROR_THIS_BRAND_IS_BEING_USED = 'ERROR_THIS_BRAND_IS_BEING_USED';

// SUCCESS
export const CREATE_BANRD_SUCCESS = 'CREATE_BANRD_SUCCESS';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const GET_BRAND_SUCCESSS = 'GET_BRAND_SUCCESSS';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_BY_CATEGORY_SUCCESS = 'GET_BRANDS_BY_CATEGORY_SUCCESS';
export const GET_BRANDS_RANKING_SELL_SUCCESS =
  'GET_BRANDS_RANKING_SELL_SUCCESS';
export const GET_BRAND_NAME_BY_ID_SUCCESS = 'GET_BRAND_NAME_BY_ID_SUCCESS';
