// ERROR
export const ERROR_CREATE_BRAND = 'ERROR_CREATE_BRAND';
export const ERROR_BRAND_NAME_EXISTED = 'ERROR_BRAND_NAME_EXISTED';
export const ERROR_UPDATE_BRAND = 'ERROR_UPDATE_BRAND';
export const ERROR_BRAND_NOT_EXIST = 'ERROR_BRAND_NOT_EXIST';
export const ERROR_NO_FIELD_TO_UPDATE = 'ERROR_NO_FIELD_TO_UPDATE';
export const ERROR_DELETE_BRAND = 'ERROR_DELETE_BRAND';
export const ERROR_GET_BRAND = 'ERROR_GET_BRAND';
export const ERROR_GET_BRANDS = 'ERROR_GET_BRANDS';
export const ERROR_GET_BRANDS_BY_CATEGORY = 'ERROR_GET_BRANDS_BY_CATEGORY';

// SUCCESS
export const CREATE_BANRD_SUCCESS = 'CREATE_BANRD_SUCCESS';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const GET_BRAND_SUCCESSS = 'GET_BRAND_SUCCESSS';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_BY_CATEGORY_SUCCESS = 'GET_BRANDS_BY_CATEGORY_SUCCESS';
