// ERROR
export const ERROR_CREATE_CATEGORY = 'ERROR_CREATE_CATEGORY';
export const ERROR_CATEGORY_EXISTED = 'ERROR_CATEGORY_EXISTED';
export const ERROR_GET_CATEGORY_LEAF = 'ERROR_GET_CATEGORY_LEAF';
export const ERROR_GET_CATEGORIES = 'ERROR_GET_CATEGORIES';
export const ERROR_DELETE_CATEGORY = 'ERROR_DELETE_CATEGORY';

// SUCCESS
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const GET_CATEGORY_LEAF_SUCCESS = 'GET_CATEGORY_LEAF_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
