//SUCCESS
export const CREATE_ROOT_CATEGORY_SUCCESS = 'CREATE_ROOT_CATEGORY_SUCCESS';
export const UPDATE_ROOT_CATEGORY_SUCCESS = 'UPDATE_ROOT_CATEGORY_SUCCESS';

//ERROR
export const ERROR_CREATE_ROOT_CATEGORY = 'ERROR_CREATE_ROOT_CATEGORY';
export const ERROR_CATEGORY_NOT_FOUND = 'ERROR_CATEGORY_NOT_FOUND';
export const ERROR_UPDATE_ROOT_CATEGORY = 'ERROR_UPDATE_ROOT_CATEGORY';
