// ERROR
export const ERROR_CREATE_CATEGORY = 'ERROR_CREATE_CATEGORY';
export const ERROR_CATEGORY_EXISTED = 'ERROR_CATEGORY_EXISTED';
export const ERROR_GET_CATEGORY_LEAF = 'ERROR_GET_CATEGORY_LEAF';
export const ERROR_GET_CATEGORIES = 'ERROR_GET_CATEGORIES';
export const ERROR_DELETE_CATEGORY = 'ERROR_DELETE_CATEGORY';
export const ERROR_THIS_VI_NAME_HAS_ALREADY_BEEN_USED =
  'ERROR_THIS_VI_NAME_HAS_ALREADY_BEEN_USEDS';
export const ERROR_THIS_EN_NAME_HAS_ALREADY_BEEN_USED =
  'ERROR_THIS_EN_NAME_HAS_ALREADY_BEEN_USEDS';
export const ERROR_UPDATE_CATEGORY_CHILD = 'ERROR_UPDATE_CATEGORY_CHILD';

// SUCCESS
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const GET_CATEGORY_LEAF_SUCCESS = 'GET_CATEGORY_LEAF_SUCCESS';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_CHILD_SUCCESS = 'UPDATE_CATEGORY_CHILD_SUCCESS';
