// SUCCESS
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';

//ERROR
export const ERROR_CREATE_ORDER_ITEM = 'ERROR_CREATE_ORDER_ITEM';
export const ERROR_CREATE_ORDER = 'ERROR_CREATE_ORDER';
export const ERROR_NOT_ENOUGH_QUANTITY_FOR_ = 'ERROR_NOT_ENOUGH_QUANTITY_FOR_';
export const ERROR_GET_ORDERS = 'ERROR_GET_ORDERS';
export const ERROR_GET_ORDER_BY_ID = 'ERROR_GET_ORDER_BY_ID';
