// SUCCESS
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

//ERROR
export const ERROR_CREATE_ORDER_ITEM = 'ERROR_CREATE_ORDER_ITEM';
export const ERROR_CREATE_ORDER = 'ERROR_CREATE_ORDER';
export const ERROR_NOT_ENOUGH_QUANTITY_FOR_ = 'ERROR_NOT_ENOUGH_QUANTITY_FOR_';
