// SUCCESS
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const USER_REJECT_PAY_WITH_MOMO = 'USER_REJECT_PAY_WITH_MOMO';
export const PAYMENT_WITH_MOMO_SUCCESS = 'PAYMENT_WITH_MOMO_SUCCESS';
export const CHECK_ORDER_SUCCESS = 'CHECK_ORDER_SUCCESS';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const GET_ORDERS_TABLE_DASHBOARD_SUCCESS =
  'GET_ORDERS_TABLE_DASHBOARD_SUCCESS';
export const REFUND_PAYMENT_WITH_MOMO_SUCCESS =
  'REFUND_PAYMENT_WITH_MOMO_SUCCESS';
export const GET_ORDER_REVENUE_FOLLOW_TIME_SUCCESS =
  'GET_ORDER_REVENUE_FOLLOW_TIME_SUCCESS';
export const GET_ORDER_OVERVIEW_SUCCESS = 'GET_ORDER_OVERVIEW_SUCCESS';
export const GET_ORDER_REPORT_DAILY_SUCCESS = 'GET_ORDER_REPORT_DAILY_SUCCESS';
export const GET_SELLING_PRODUCTS_FOLLOW_TIME_SUCCESS =
  'GET_SELLING_PRODUCTS_FOLLOW_TIME_SUCCESS';

//ERROR
export const ERROR_CREATE_ORDER_ITEM = 'ERROR_CREATE_ORDER_ITEM';
export const ERROR_CREATE_ORDER = 'ERROR_CREATE_ORDER';
export const ERROR_NOT_ENOUGH_QUANTITY_FOR_ = 'ERROR_NOT_ENOUGH_QUANTITY_FOR_';
export const ERROR_GET_ORDERS = 'ERROR_GET_ORDERS';
export const ERROR_GET_ORDER_BY_ID = 'ERROR_GET_ORDER_BY_ID';
export const ERROR_MAKE_PAYMENT_WITH_MOMO = 'ERROR_MAKE_PAYMENT_WITH_MOMO';
export const ERROR_CHECK_ORDER = 'ERROR_CHECK_ORDER';
export const ERROR_UPDATE_ORDER_STATUS = 'ERROR_UPDATE_ORDER_STATUS';
export const ERROR_ORDER_NOT_FOUND = 'ERROR_ORDER_NOT_FOUND';
export const ERROR_CAN_NOT_UPDATE_ORDER_STATUS =
  'ERROR_CAN_NOT_UPDATE_ORDER_STATUS';
export const ERROR_GET_ORDERS_TABLE_DASHBOARD =
  'ERROR_GET_ORDERS_TABLE_DASHBOARD';
export const ERROR_REFUND_PAYMENT_WITH_MOMO_ORDER =
  'ERROR_REFUND_PAYMENT_WITH_MOMO_ORDER';
export const ERROR_CAN_NOT_REFUND_COD_PAYMENT_METHOD =
  'ERROR_CAN_NOT_REFUND_COD_PAYMENT_METHOD';
export const ERROR_GET_ORDER_REVENUE_FOLLOW_TIME =
  'ERROR_GET_ORDER_REVENUE_FOLLOW_TIME';
export const ERROR_GET_ORDER_OVERVIEW = 'ERROR_GET_ORDER_OVERVIEW';
export const ERROR_GET_ORDER_REPORT_DAILY = 'ERROR_GET_ORDER_REPORT_DAILY';
export const ERROR_GET_SELLING_PRODUCTS_FOLLOW_TIME =
  'ERROR_GET_SELLING_PRODUCTS_FOLLOW_TIME';
