// SUCCESS
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ITEM_SUCCESS = 'CREATE_PRODUCT_ITEM_SUCCESS';
export const GET_PRODUCT_NAMES_SUCCESS = 'GET_PRODUCT_NAMES_SUCCESS';
export const GET_PRODUCT_DASHBOARD_TABLE_SUCCESS =
  'GET_PRODUCT_DASHBOARD_TABLE_SUCCESS';

// ERROR
export const ERROR_PRODUCT_EXISTED = 'ERROR_PRODUCT_EXISTED';
export const ERROR_CREATE_PRODUCT = 'ERROR_CREATE_PRODUCT';
export const ERROR_PRODUCT_ITEM_EXISTED = 'ERROR_PRODUCT_ITEM_EXISTED';
export const ERROR_CREATE_PRODUCT_ITEM = 'ERROR_CREATE_PRODUCT_ITEM';
export const ERROR_GET_PRODUCT_NAMES = 'ERROR_GET_PRODUCT_NAMES';
export const ERROR_GET_PRODUCT_DASHBOARD_TABLE =
  'ERROR_GET_PRODUCT_DASHBOARD_TABLE';
