// SUCCESS
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ITEM_SUCCESS = 'CREATE_PRODUCT_ITEM_SUCCESS';

// ERROR
export const ERROR_PRODUCT_EXISTED = 'ERROR_PRODUCT_EXISTED';
export const ERROR_CREATE_PRODUCT = 'ERROR_CREATE_PRODUCT';
export const ERROR_PRODUCT_ITEM_EXISTED = 'ERROR_PRODUCT_ITEM_EXISTED';
export const ERROR_CREATE_PRODUCT_ITEM = 'ERROR_CREATE_PRODUCT_ITEM';
