// SUCCESS
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_ITEM_SUCCESS = 'CREATE_PRODUCT_ITEM_SUCCESS';
export const GET_PRODUCT_NAMES_SUCCESS = 'GET_PRODUCT_NAMES_SUCCESS';
export const GET_PRODUCT_DASHBOARD_TABLE_SUCCESS =
  'GET_PRODUCT_DASHBOARD_TABLE_SUCCESS';
export const DELETE_PRODUCT_ITEM_SUCCESS = 'DELETE_PRODUCT_ITEM_SUCCESS';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const FIND_PRODUCT_ITEM_BY_ID_SUCCESS =
  'FIND_PRODUCT_ITEM_BY_ID_SUCCESS';
export const UPDATE_PRODUCT_ITEM_SUCCESS = 'UPDATE_PRODUCT_ITEM_SUCCESS';
export const GET_PRODUCT_ITEM_SUCCESS = 'GET_PRODUCT_ITEM_SUCCESS';
export const GET_PRODUCT_ITEM_DETAIL_SUCCESS =
  'GET_PRODUCT_ITEM_DETAIL_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_SUCCESS =
  'GET_PRODUCT_BY_CATEGORY_SUCCESS';
export const GET_PRODUCT_BY_CATEGORY_AND_OPTIONS_SUCCESS =
  'GET_PRODUCT_BY_CATEGORY_AND_OPTIONS_SUCCESS';
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS';
export const GET_RECOMMEND_CF_SUCCESS = 'GET_RECOMMEND_CF_SUCCESS';
export const ADD_PROD_ITEM_QUANTITY_SUCCESS = 'ADD_PROD_ITEM_QUANTITY_SUCCESS';

// ERROR
export const ERROR_PRODUCT_EXISTED = 'ERROR_PRODUCT_EXISTED';
export const ERROR_CREATE_PRODUCT = 'ERROR_CREATE_PRODUCT';
export const ERROR_PRODUCT_ITEM_EXISTED = 'ERROR_PRODUCT_ITEM_EXISTED';
export const ERROR_CREATE_PRODUCT_ITEM = 'ERROR_CREATE_PRODUCT_ITEM';
export const ERROR_GET_PRODUCT_NAMES = 'ERROR_GET_PRODUCT_NAMES';
export const ERROR_GET_PRODUCT_DASHBOARD_TABLE =
  'ERROR_GET_PRODUCT_DASHBOARD_TABLE';
export const ERROR_DELETE_PRODUCT_ITEM = 'ERROR_DELETE_PRODUCT_ITEM';
export const ERROR_DELETE_PRODUCT = 'ERROR_DELETE_PRODUCT';
export const ERROR_FIND_PRODUCT_BY_ID = 'ERROR_FIND_PRODUCT_BY_ID';
export const ERROR_PRODUCT_NOT_FOUND = 'ERROR_PRODUCT_NOT_FOUND';
export const ERROR_UPDATE_PRODUCT = 'ERROR_UPDATE_PRODUCT';
export const ERROR_FIND_PRODUCT_ITEM = 'ERROR_FIND_PRODUCT_ITEM';
export const ERROR_UPDATE_PRODUCT_ITEM = 'ERROR_UPDATE_PRODUCT_ITEM';
export const ERROR_GET_PRODUCT_ITEM = 'ERROR_GET_PRODUCT_ITEM';
export const ERROR_GET_PRODUCT_ITEM_DETAIL = 'ERROR_GET_PRODUCT_ITEM_DETAIL';
export const ERROR_GET_PRODUCT_BY_CATEGORY = 'ERROR_GET_PRODUCT_BY_CATEGORY';
export const ERROR_GET_PRODUCT_BY_CATEGORY_AND_OPTIONS =
  'ERROR_GET_PRODUCT_BY_CATEGORY_AND_OPTIONS';
export const ERROR_SEARCH_PRODUCT = 'ERROR_SEARCH_PRODUCT';
export const ERROR_GET_RECOMMEND_CF = 'ERROR_GET_RECOMMEND_CF';
export const ERROR_ADD_PROD_ITEM_QUANTITY = 'ERROR_ADD_PROD_ITEM_QUANTITY';
