// SUCCESS
export const GET_SHIPPING_FEE_PER_KM_SUCCESS =
  'GET_SHIPPING_FEE_PER_KM_SUCCESS';
export const UPDATE_SHIPPING_FEE_PER_KM_SUCCESS =
  'UPDATE_SHIPPING_FEE_PER_KM_SUCCESS';

// ERROR
export const ERROR_GET_SHIPPING_FEE_PER_KM = 'ERROR_GET_SHIPPING_FEE_PER_KM';
export const ERROR_UPDATE_SHIPPING_FEE_PER_KM =
  'ERROR_UPDATE_SHIPPING_FEE_PER_KM';
