// SUCCESS
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS';
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const CREATE_TAG_GROUP_SUCCESS = 'CREATE_TAG_GROUP_SUCCESS';
export const UPDATE_TAG_GROUP_SUCCESS = 'UPDATE_TAG_GROUP_SUCCESS';

// ERROR
export const ERROR_CREATE_TAG = 'ERROR_CREATE_TAG';
export const ERROR_TAG_NOT_FOUND = 'ERROR_TAG_NOT_FOUND';
export const ERROR_UPDATE_TAG = 'ERROR_UPDATE_TAG';
export const ERROR_DELETE_TAG = 'ERROR_DELETE_TAG';
export const ERROR_TAG_EXISTED = 'ERROR_TAG_EXISTED';
export const ERROR_GET_TAGS = 'ERROR_GET_TAGS';
export const ERROR_TAG_GROUP_EXISTED = 'ERROR_TAG_GROUP_EXISTED';
export const ERROR_CREATE_TAG_GROUP = 'ERROR_CREATE_TAG_GROUP';
export const ERROR_TAG_GROUP_NOT_EXIST = 'ERROR_TAG_GROUP_NOT_EXIST';
export const ERROR_UPDATE_TAG_GROUP = 'ERROR_UPDATE_TAG_GROUP';
