//SUCCESS
export const GET_USER_BY_EMAIL_SUCCESS = 'GET_USER_BY_EMAIL_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';

//ERROR
export const ERROR_GET_USER_BY_EMAIL = 'ERROR_GET_USER_BY_EMAIL';
export const ERROR_UPDATE_USER = 'ERROR_UPDATE_USER';
export const ERROR_CHANGE_PASS = 'ERROR_CHANGE_PASS';
