//SUCCESS
export const GET_USER_BY_EMAIL_SUCCESS = 'GET_USER_BY_EMAIL_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CHANGE_DEFAULT_ADDRESS_SUCCESS = 'CHANGE_DEFAULT_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const CHECK_USER_HAS_PASS_SUCCESS = 'CHECK_USER_HAS_PASS_SUCCESS';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';

//ERROR
export const ERROR_GET_USER_BY_EMAIL = 'ERROR_GET_USER_BY_EMAIL';
export const ERROR_UPDATE_USER = 'ERROR_UPDATE_USER';
export const ERROR_CHANGE_PASS = 'ERROR_CHANGE_PASS';
export const ERROR_CREATE_ADDRESS = 'ERROR_CREATE_ADDRESS';
export const ERROR_UPDATE_ADDRESS = 'ERROR_UPDATE_ADDRESS';
export const ERROR_CHANGE_DEFAULT_ADDRESS = 'ERROR_CHANGE_DEFAULT_ADDRESS';
export const ERROR_DELETE_ADDRESS = 'ERROR_DELETE_ADDRESS';
export const ERROR_ADDRESS_NOT_FOUND = 'ERROR_ADDRESS_NOT_FOUND';
export const ERROR_DO_NOT_DELETE_DEFAULT_ADDREESS =
  'ERROR_DO_NOT_DELETE_DEFAULT_ADDREESS';
export const ERROR_CHECK_USER_HAS_PASS = 'ERROR_CHECK_USER_HAS_PASS';
export const ERROR_CREATE_PASSWORD = 'ERROR_CREATE_PASSWORD';
