//SUCCESS
export const CREATE_VARIATION_SUCCESS = 'CREATE_VARIATION_SUCCESS';
export const CREATE_VARIATION_OPTION_SUCCESS =
  'CREATE_VARIATION_OPTION_SUCCESS';
export const GET_VARIATION_SUCCESS = 'GET_VARIATION_SUCCESS';
export const GET_VARIATION_OPTION_SUCCESS = 'GET_VARIATION_OPTION_SUCCESS';
export const GET_VARIATION_TABLE_SUCCESS = 'GET_VARIATION_TABLE_SUCCESS';
export const DELETE_VARIATION_OPTION_SUCCESS =
  'DELETE_VARIATION_OPTION_SUCCESS';
export const DELETE_VARIATION_SUCCESS = 'DELETE_VARIATION_SUCCESS';

//ERROR
export const ERROR_CREATE_VARIATION = 'ERROR_CREATE_VARIATION';
export const ERROR_VARIATION_EXISTED = 'ERROR_VARIATION_EXISTED';
export const ERROR_VARIATION_OPTION_EXISTED = 'ERROR_VARIATION_OPTION_EXISTED';
export const ERROR_CREATE_VARIATION_OPTION = 'ERROR_CREATE_VARIATION_OPTION';
export const ERROR_GET_VARIATION = 'ERROR_GET_VARIATION';
export const ERROR_GET_VARIATION_OPTION = 'ERROR_GET_VARIATION_OPTION';
export const ERROR_GET_VARIATION_TABLE = 'ERROR_GET_VARIATION_TABLE';
export const ERROR_DELETE_VARIATION_OPTION = 'ERROR_DELETE_VARIATION_OPTION';
export const ERROR_THIS_OPTION_IS_BEING_USED =
  'ERROR_THIS_OPTIONS_IS_BEING_USED';
export const ERROR_DELETE_VARIATION = 'ERROR_DELETE_VARIATION';
