//SUCCESS
export const CREATE_VARIATION_SUCCESS = 'CREATE_VARIATION_SUCCESS';
export const CREATE_VARIATION_OPTION_SUCCESS =
  'CREATE_VARIATION_OPTION_SUCCESS';

//ERROR
export const ERROR_CREATE_VARIATION = 'ERROR_CREATE_VARIATION';
export const ERROR_VARIATION_EXISTED = 'ERROR_VARIATION_EXISTED';
export const ERROR_VARIATION_OPTION_EXISTED = 'ERROR_VARIATION_OPTION_EXISTED';
export const ERROR_CREATE_VARIATION_OPTION = 'ERROR_CREATE_VARIATION_OPTION';
